workspace:
  path: /data
 
registry:
  - name: alpine
    settings:
      auto_tag: true
      dockerfile: ./Dockerfile
      context: .
    when:
      branch:
        - master
      event:
        - push
